name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        extra_nix_config: |
          trusted-public-keys = chaostomato.cachix.org-1:MtFdKLf8Hkmsih2TNxX8X3mnQdR0Xr8+BHpQoVr1TE8= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://chaostomato.cachix.org https://cache.nixos.org/
    - run: nix-build -A pkgsStatic.chaostomato
    - uses: actions/upload-artifact@v2
      with:
        name: static-binary
        path: result/bin/chaostomato
